version: '3.8'
services:
  newsapp:
    build: ./NewsApp
    container_name: newsApp
    ports:
      - "3001:3001"
    restart: on-failure
    networks:
      - newsApp
  
  newapp-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3001",
        "-app-id", "newsApp",
        "-app-protocol", "http",
        "-dapr-http-port", "3501",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - newsApp
    network_mode: "service:newsApp"
  
  user:
    build: ./User
    container_name: user
    ports:
      - "3002:3002"
    restart: on-failure
    networks:
      - newsApp

  user-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3002",
        "-app-id", "user",
        "-app-protocol", "http",
        "-dapr-http-port", "3502",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - user
    network_mode: "service:user"
  
  userAccessor:
    build: ./userAccessor
    container_name: userAccessor
    ports:
      - "3003:3003"
    restart: on-failure
    networks:
      - newsApp

  userAccessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3003",
        "-app-id", "userAccessor",
        "-app-protocol", "http",
        "-dapr-http-port", "3503",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - userAccessor
    network_mode: "service:userAccessor"

  mongodb:
    image: mongo:latest
    container_name: mongoDb
    ports:
      - 27018:27017
    networks:
      - newsApp 

networks:
  newsApp: