version: '3.8'
services:
  newsapp:
    build: ./NewsApp
    container_name: newsApp
    ports:
      - "3001:3001"
    restart: on-failure
    env_file:
      - ./NewsApp/.env
    networks:
      - newsApp
  
  newapp-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3001",
        "-app-id", "newsApp",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "--resources-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        "--log-level", "debug",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - newsapp
    network_mode: "service:newsapp"
  
  user:
    build: ./User
    container_name: user
    ports:
      - "3002:3002"
    restart: on-failure
    env_file:
      - ./User/.env
    networks:
      - newsApp

  user-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3002",
        "-app-id", "user",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "--resources-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        "--log-level", "debug",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - user
    network_mode: "service:user"
  
  useraccessor:
    build: ./UserAccessor
    container_name: userAccessor
    ports:
      - "3003:3003"
    restart: on-failure
    env_file:
      - ./UserAccessor/.env
    networks:
      - newsApp

  useraccessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3003",
        "-app-id", "useraccessor",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "--resources-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        "--log-level", "debug",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - useraccessor
    network_mode: "service:useraccessor"

  newsdata:
    build: ./NewsData
    container_name: newsData
    ports:
      - "3004:3004"
    restart: on-failure
    env_file:
      - ./NewsData/.env
    networks:
      - newsApp
  
  newsdata-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3004",
        "-app-id", "newsdata",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "--resources-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        "--log-level", "debug",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - newsdata
    network_mode: "service:newsdata"

  newsai:
    build: ./NewsAi
    container_name: newsAi
    ports:
      - "3005:3005"
    restart: on-failure
    env_file:
      - ./NewsAi/.env
    networks:
      - newsApp
  
  newsai-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3005",
        "-app-id", "newsai",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "--resources-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        "--log-level", "debug",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - newsai
    network_mode: "service:newsai"

  email:
    build: ./Email
    container_name: email
    ports:
      - "3006:3006"
    restart: on-failure
    env_file:
      - ./Email/.env
    networks:
      - newsApp
  
  email-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "3006",
        "-app-id", "email",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "--resources-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        "--log-level", "debug",
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - email
    network_mode: "service:email"

  mongodb:
    image: mongo:latest
    container_name: mongoDb
    ports:
      - 27018:27017
    networks:
      - newsApp 

  test-runner:
    image: node:20.10.0
    volumes:
      - ./tests:/tests
      - ./test-runner:/test-runner
      - ./NewsApp:/NewsApp
      - ./User:/User
      - ./UserAccessor:/UserAccessor
      - ./NewsData:/NewsData
      - ./NewsAi:/NewsAi
      - ./Email:/Email
    networks:
      - newsApp
    depends_on:
      - newsapp
      - user
      - useraccessor
      - newsdata
      - newsai
      - email
    working_dir: /test-runner
    command: ["sh", "-c", "sleep 120 && npm test"]

networks:
  newsApp:
    driver: bridge